### ISSUE TITLE
Options not showing up in field

### ISSUE THREAD

**Issue by ewarrin** [bostondv/acf-ninja-forms#1]
I have three forms built but none are showing up in the selection field for Ninja Forms.

It is outputting this code.

```
<select name="acf[field_57e0760e79a8e]" id="acf[field_57e0760e79a8e]">
                    <option value="1">
                          </option>
                      <option value="2">
                          </option>
                      <option value="3">
                          </option>
                </select>
```

Here is a screenshot [http://dev.walltribe.com/wp-content/uploads/2016/09/screencapture-dev-walltribe-wp-admin-post-new-php-1474330252484.png]

Let me know if I am doing something wrong.

Thanks a ton for this plugin.

Eric

**Comment by mizukimadness** [comment]
I have the same problem. It also says:
`Notice: Undefined index: form_title in /Applications/XAMPP/xamppfiles/htdocs/pantbanken/wp-content/plugins/acf-ninja-form/acf-ninja-forms-field-v5.php on line 112`

**Comment by JacobDB** [comment]
This could be due to Ninja Forms being updated to v3. I'm having the same issue.
